/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentAuthRouteImport } from './routes/student-auth'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as ApiLibraryChatRouteImport } from './routes/api/library-chat'

const StudentAuthRoute = StudentAuthRouteImport.update({
  id: '/student-auth',
  path: '/student-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const ApiLibraryChatRoute = ApiLibraryChatRouteImport.update({
  id: '/api/library-chat',
  path: '/api/library-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/student-auth': typeof StudentAuthRoute
  '/api/library-chat': typeof ApiLibraryChatRoute
  '/student/profile': typeof StudentProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/student-auth': typeof StudentAuthRoute
  '/api/library-chat': typeof ApiLibraryChatRoute
  '/student/profile': typeof StudentProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/student-auth': typeof StudentAuthRoute
  '/api/library-chat': typeof ApiLibraryChatRoute
  '/student/profile': typeof StudentProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee'
    | '/sitemap.xml'
    | '/student'
    | '/student-auth'
    | '/api/library-chat'
    | '/student/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employee'
    | '/sitemap.xml'
    | '/student'
    | '/student-auth'
    | '/api/library-chat'
    | '/student/profile'
  id:
    | '__root__'
    | '/'
    | '/employee'
    | '/sitemap.xml'
    | '/student'
    | '/student-auth'
    | '/api/library-chat'
    | '/student/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRoute: typeof EmployeeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentRoute: typeof StudentRouteWithChildren
  StudentAuthRoute: typeof StudentAuthRoute
  ApiLibraryChatRoute: typeof ApiLibraryChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-auth': {
      id: '/student-auth'
      path: '/student-auth'
      fullPath: '/student-auth'
      preLoaderRoute: typeof StudentAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/api/library-chat': {
      id: '/api/library-chat'
      path: '/api/library-chat'
      fullPath: '/api/library-chat'
      preLoaderRoute: typeof ApiLibraryChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentRouteChildren {
  StudentProfileRoute: typeof StudentProfileRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentProfileRoute: StudentProfileRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRoute: EmployeeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentRoute: StudentRouteWithChildren,
  StudentAuthRoute: StudentAuthRoute,
  ApiLibraryChatRoute: ApiLibraryChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
